import { createUseStyles } from "react-jss";

export default createUseStyles({
  item: {
    width: "100%",
    minHeight: 60,
    flex: 1,
    background: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: [0, 16],
    transition: "all 250ms ease",
    "&:hover": {
      backgroundColor: "#f9f9f9",
    },
  },
  placeTitle: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-start",
    flex: 3,
    height: 30,
    background: "#ddd",
    borderRadius: 2,
    maxWidth: 400,
  },
  placeAuthor: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flex: 3,
    height: 30,
    background: "#ddd",
    borderRadius: 2,
    maxWidth: 200,
  },
  placeCreateDate: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flex: 3,
    height: 30,
    background: "#ddd",
    borderRadius: 2,
    maxWidth: 200,
  },
  placeTools: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-around",
    flex: 1,
    height: 30,
    background: "#ddd",
    borderRadius: 2,
    maxWidth: 150,
  },
  borderLine: {
    borderBottom: [1, "solid", "#f5f5f5"],
  },
  contentWrapper: {
    display: "flex",
    width: "100%",
    flex: 1,
    maxHeight: "calc(100% - 80px)",
    justifyContent: "flex-start",
    alignItems: "center",
    flexDirection: "column",
    overflowX: "hidden",
    overflowY: "auto",
  },
});
